In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
df = pd.read_csv("https://cos.colordi.top/Dataset/spider.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Girdled  37 non-null     int64
 1   Logged   37 non-null     int64
dtypes: int64(2)
memory usage: 720.0 bytes


In [6]:
# 接下来我想要用r里面的iNEXT包来计算一些多样性指数的估计值：
from rpy2.robjects import r
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
pandas2ri.activate()
# r['install.packages']('iNEXT') # 安装包
inext = importr("iNEXT") #library R package

result = inext.iNEXT(df)
result
print(result)

Compare 2 assemblages with Hill number order q = 0.
$class: iNEXT

$DataInfo: basic data information
     site   n S.obs     SC f1 f2 f3 f4 f5 f6 f7 f8 f9 f10
1 Girdled 168    26 0.9289 12  4  0  1  0  2  0  1  1   0
2  Logged 252    37 0.9446 14  4  4  3  1  0  3  2  0   1

$iNextEst: diversity estimates with rarefied and extrapolated samples.
$Girdled
     m       method order     qD qD.LCL qD.UCL    SC SC.LCL SC.UCL
1    1 interpolated     0  1.000  1.000  1.000 0.122  0.101  0.143
10  84 interpolated     0 18.912 16.295 21.530 0.900  0.871  0.928
20 168     observed     0 26.000 21.680 30.320 0.929  0.903  0.955
30 248 extrapolated     0 30.883 24.998 36.769 0.948  0.918  0.979
40 336 extrapolated     0 34.731 26.854 42.607 0.964  0.932  0.995

$Logged
     m       method order     qD qD.LCL qD.UCL    SC SC.LCL SC.UCL
1    1 interpolated     0  1.000  1.000  1.000 0.145  0.106  0.183
10 126 interpolated     0 28.268 25.416 31.119 0.908  0.887  0.929
20 252     observed     0 37.000

In [9]:
# 你会发现，result是一个R里面的list类型，它有3个子对象，这一点和在R中运行是一样的，只不过在R中会直接打印出这三个对象，
# 当然你如果使用python的print(result)也可以一样的显示。你当然可以凭直觉对这个list对象进行python的列表取元素操作：

In [11]:
# 我们可以发现，取出的结果自动变成了pandas里的DataFrame类型了(type()函数已经给出了），接下来你完全可以对这个
# DataFrame进行一套你在Python里刻在DNA里的分析了。
print(type(result[0]))

<class 'pandas.core.frame.DataFrame'>


In [10]:
df = result[0]
df

site      n  S.obs      SC    f1   f2   f3   f4   f5   f6   f7   f8  \
1  Girdled  168.0   26.0  0.9289  12.0  4.0  0.0  1.0  0.0  2.0  0.0  1.0   
2   Logged  252.0   37.0  0.9446  14.0  4.0  4.0  3.0  1.0  0.0  3.0  2.0   

    f9  f10  
1  1.0  0.0  
2  0.0  1.0

## 详细解释

In [12]:
# 详细解释
# 上述是一个简单的例子，我们现在来看一下这里面的代码，不难发现，基本上所有的代码都是围绕rpy2.robjects来运行的。实际上我们基本也只会用到它。
from rpy2.robjects import r

In [13]:
r('c(1,2,3)')

array([1., 2., 3.])

In [14]:
print(type((r('c(1,2,3)'))))

<class 'numpy.ndarray'>


In [15]:
# 可以看到，返回的是一个ndarrray数组，这是因为rpy2是基于numpy的，所以一般而言返回的对象都是数组形式。
# 其实，还可以使用字典形式和.方法调用属性的方法来使用r:

In [16]:
r['pi']

array([3.14159265])

In [17]:
r.c(1,2,3)

array([1, 2, 3], dtype=int32)

In [18]:
rscript = """
a <- c(1,2,3,4)
b <- c(2,4,6,8)
fit <- lm(b~a)
summary(fit)
"""
print(r(rscript))


Call:
lm(formula = b ~ a)

Residuals:
1 2 3 4 
0 0 0 0 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)        0          0     NaN      NaN    
a                  2          0     Inf   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0 on 2 degrees of freedom
Multiple R-squared:      1,	Adjusted R-squared:      1 
F-statistic:   Inf on 1 and 2 DF,  p-value: < 2.2e-16




## 导入R包
光用简单的R语句肯定是不符合我们的需求的，我们在Python中用R最大的目的就是用一些R的三方包嘛，这里就有了第二个语句：

In [ ]:
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
pandas2ri.activate()

inext = importr("iNEXT")
result = inext.iNEXT(df)

In [39]:
import pandas as pd
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
pandas2ri.activate()

df = pd.read_csv("https://cos.colordi.top/Dataset/spider.csv")
inext = importr("iNEXT")
ggplot2 = importr('ggplot2')
result = inext.iNEXT(df)
figure = inext.ggiNEXT(result)
ggplot2.ggsave('test.pdf',plot=figure)

R[write to console]: Saving 7 x 7 in image



<rpy2.robjects.vectors.StrVector object at 0x7fe0a0414280> [RTYPES.STRSXP]
R classes: ('character',)
['test.pdf']

In [36]:
import pandas as pd
from rpy2.robjects.lib import grdevices
from IPython.display import Image,display
from rpy2.robjects.packages import importr


ggplot2 = importr('ggplot2')

with grdevices.render_to_bytesio(grdevices.jpeg,width=300,height=300) as img:
    x=inext.ggiNEXT(result)
    ggplot2.ggsave('1.png',plot=x)
display(Image(data=img.getvalue(),format='jpeg',embed=True))

R[write to console]: Saving 4.17 x 4.17 in image

